// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-R97fasNggwtq1LVLCXkGkcX5E35h0s',
    appId: '1:1089073341381:web:51b0b6568f85b4996b61ac',
    messagingSenderId: '1089073341381',
    projectId: 'fir-app-8a815',
    authDomain: 'fir-app-8a815.firebaseapp.com',
    storageBucket: 'fir-app-8a815.appspot.com',
    measurementId: 'G-ZQCF48GV4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7FkIik664b8fBwN01JZsmvrGFsyOxWxY',
    appId: '1:1089073341381:android:8c03d832a3aae1ed6b61ac',
    messagingSenderId: '1089073341381',
    projectId: 'fir-app-8a815',
    storageBucket: 'fir-app-8a815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA02Cbjudy3y_yB37HkiMEjGTka7szQlOo',
    appId: '1:1089073341381:ios:e97146e4bebd03816b61ac',
    messagingSenderId: '1089073341381',
    projectId: 'fir-app-8a815',
    storageBucket: 'fir-app-8a815.appspot.com',
    iosBundleId: 'com.example.firebasedeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA02Cbjudy3y_yB37HkiMEjGTka7szQlOo',
    appId: '1:1089073341381:ios:e97146e4bebd03816b61ac',
    messagingSenderId: '1089073341381',
    projectId: 'fir-app-8a815',
    storageBucket: 'fir-app-8a815.appspot.com',
    iosBundleId: 'com.example.firebasedeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA-R97fasNggwtq1LVLCXkGkcX5E35h0s',
    appId: '1:1089073341381:web:fc4071762dc2e7856b61ac',
    messagingSenderId: '1089073341381',
    projectId: 'fir-app-8a815',
    authDomain: 'fir-app-8a815.firebaseapp.com',
    storageBucket: 'fir-app-8a815.appspot.com',
    measurementId: 'G-VKVD47PYW0',
  );
}
